// This file is auto-generated by @hey-api/openapi-ts

export type GetSpellCheckData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        language_code?: string;
        text?: string;
    };
};

export type GetSpellCheckResponse = ({
    [key: string]: unknown;
});

export type GetSpellCheckError = unknown;

export type GetProfanityData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        text?: string;
    };
};

export type GetProfanityResponse = ({
    [key: string]: unknown;
});

export type GetProfanityError = unknown;

export type GetNsfwData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        url?: string;
    };
};

export type GetNsfwResponse = (unknown);

export type GetNsfwError = unknown;

export type GetValidateEmailData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        email?: string;
    };
};

export type GetValidateEmailResponse = ({
    [key: string]: unknown;
});

export type GetValidateEmailError = unknown;

export type PostSpamcheckData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
    };
};

export type PostSpamcheckResponse = ({
    [key: string]: unknown;
});

export type PostSpamcheckError = unknown;

export type GetSearchData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        ai_overview?: boolean;
        query?: string;
        safe_search?: string;
        spell_check?: boolean;
    };
};

export type GetSearchResponse = ({
    [key: string]: unknown;
});

export type GetSearchError = unknown;

export type GetSearchSuggestData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        query?: string;
    };
};

export type GetSearchSuggestResponse = ({
    [key: string]: unknown;
});

export type GetSearchSuggestError = unknown;

export type GetDnsData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        domain?: string;
        type?: string;
    };
};

export type GetDnsResponse = ({
    [key: string]: unknown;
});

export type GetDnsError = unknown;

export type PostHtmlToAnyData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
    };
};

export type PostHtmlToAnyResponse = (unknown);

export type PostHtmlToAnyError = unknown;

export type PostScrapeData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
    };
};

export type PostScrapeResponse = (unknown);

export type PostScrapeError = unknown;

export type PostAiScrapeData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
    };
};

export type PostAiScrapeResponse = ({
    [key: string]: unknown;
});

export type PostAiScrapeError = unknown;

export type PostStoreKvData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
    };
};

export type PostStoreKvResponse = ({
    [key: string]: unknown;
});

export type PostStoreKvError = unknown;

export type GetStoreKv39Jd883Data = {
    headers?: {
        'x-api-key'?: string;
    };
};

export type GetStoreKv39Jd883Response = ({
    [key: string]: unknown;
});

export type GetStoreKv39Jd883Error = unknown;

export type DeleteFileHelloData = {
    headers?: {
        'x-api-key'?: string;
    };
};

export type DeleteFileHelloResponse = ({
    [key: string]: unknown;
});

export type DeleteFileHelloError = unknown;

export type PostStoreFileData = {
    body?: {
        'file.png'?: (Blob | File);
    };
    query?: {
        key?: string;
    };
};

export type PostStoreFileResponse = (unknown);

export type PostStoreFileError = unknown;

export type GetStoreFileByKeyData = {
    path: {
        key: string;
    };
};

export type GetStoreFileByKeyResponse = (unknown);

export type GetStoreFileByKeyError = unknown;

export type PostObjectDetectionData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
    };
};

export type PostObjectDetectionResponse = ({
    [key: string]: unknown;
});

export type PostObjectDetectionError = unknown;

export type PostData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
    };
};

export type PostResponse = ({
    [key: string]: unknown;
});

export type PostError = unknown;

export type GetGeoCityData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        country_code?: string;
    };
};

export type GetGeoCityResponse = (unknown);

export type GetGeoCityError = unknown;

export type GetGeoCountryData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        country_code?: string;
    };
};

export type GetGeoCountryResponse = (unknown);

export type GetGeoCountryError = unknown;

export type GetGeoStateData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        country_code?: string;
    };
};

export type GetGeoStateResponse = (unknown);

export type GetGeoStateError = unknown;

export type GetGeoDistanceData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        lat1?: number;
        lat2?: number;
        lng1?: number;
        lng2?: number;
    };
};

export type GetGeoDistanceResponse = ({
    [key: string]: unknown;
});

export type GetGeoDistanceError = unknown;

export type GetGeoTimezoneData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        country_code?: string;
    };
};

export type GetGeoTimezoneResponse = ({
    [key: string]: unknown;
});

export type GetGeoTimezoneError = unknown;

export type GetGeoGeohashData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        lat?: number;
        lng?: number;
    };
};

export type GetGeoGeohashResponse = ({
    [key: string]: unknown;
});

export type GetGeoGeohashError = unknown;

export type GetGeoGeohashDecodeS1Jsf8YpfData = {
    headers?: {
        'x-api-key'?: string;
    };
};

export type GetGeoGeohashDecodeS1Jsf8YpfResponse = ({
    [key: string]: unknown;
});

export type GetGeoGeohashDecodeS1Jsf8YpfError = unknown;

export type GetGeoSearchData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        search_value?: string;
    };
};

export type GetGeoSearchResponse = (unknown);

export type GetGeoSearchError = unknown;

export type GetGeoGeocodeData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        search_value?: string;
    };
};

export type GetGeoGeocodeResponse = (unknown);

export type GetGeoGeocodeError = unknown;

export type PostTranscribeData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
    };
};

export type PostTranscribeResponse = ({
    [key: string]: unknown;
});

export type PostTranscribeError = unknown;

export type PostTtsData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
    };
};

export type PostTtsResponse = ({
    [key: string]: unknown;
});

export type PostTtsError = unknown;

export type GetTtsData = {
    headers?: {
        'x-api-key'?: string;
    };
};

export type GetTtsResponse = ({
    [key: string]: unknown;
});

export type GetTtsError = unknown;

export type PostPromptEngineData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
    };
};

export type PostPromptEngineResponse = ({
    [key: string]: unknown;
});

export type PostPromptEngineError = unknown;

export type GetPromptEngineData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        limit?: number;
        page?: number;
    };
};

export type GetPromptEngineResponse = ({
    [key: string]: unknown;
});

export type GetPromptEngineError = unknown;

export type PostPromptEngineB295D777089248E1A5F6A9Ae91E9D28AData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
    };
};

export type PostPromptEngineB295D777089248E1A5F6A9Ae91E9D28AResponse = (unknown);

export type PostPromptEngineB295D777089248E1A5F6A9Ae91E9D28AError = unknown;

export type DeletePromptEngineDc578C696Eb54C5B82Ab9F74077Cfdd5Data = {
    headers?: {
        'x-api-key'?: string;
    };
};

export type DeletePromptEngineDc578C696Eb54C5B82Ab9F74077Cfdd5Response = ({
    [key: string]: unknown;
});

export type DeletePromptEngineDc578C696Eb54C5B82Ab9F74077Cfdd5Error = unknown;

export type PostRunData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
    };
};

export type PostRunResponse = ({
    [key: string]: unknown;
});

export type PostRunError = unknown;

export type GetDc578C696Eb54C5B82Ab9F74077Cfdd5Data = {
    headers?: {
        'x-api-key'?: string;
    };
};

export type GetDc578C696Eb54C5B82Ab9F74077Cfdd5Response = ({
    [key: string]: unknown;
});

export type GetDc578C696Eb54C5B82Ab9F74077Cfdd5Error = unknown;

export type PostApiV1PromptEngineStreamingData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
        'x-jigsaw-no-request-log'?: boolean;
    };
};

export type PostApiV1PromptEngineStreamingResponse = (unknown);

export type PostApiV1PromptEngineStreamingError = unknown;

export type PostSummaryData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        text?: string;
    };
};

export type PostSummaryResponse = ({
    [key: string]: unknown;
});

export type PostSummaryError = unknown;

export type PostSentimentData = {
    headers?: {
        'x-api-key'?: string;
    };
    query?: {
        text?: string;
    };
};

export type PostSentimentResponse = ({
    [key: string]: unknown;
});

export type PostSentimentError = unknown;

export type PostTranslateData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
    };
};

export type PostTranslateResponse = ({
    [key: string]: unknown;
});

export type PostTranslateError = unknown;

export type PostSqlData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
    };
};

export type PostSqlResponse = ({
    [key: string]: unknown;
});

export type PostSqlError = unknown;

export type PostImageGenerationData = {
    body?: {
        [key: string]: unknown;
    };
    headers?: {
        'x-api-key'?: string;
    };
};

export type PostImageGenerationResponse = (unknown);

export type PostImageGenerationError = unknown;